version: "3.5"
services:
  vis-api:
    ports:
      - '3001:3001/tcp'
    volumes:
      - '../../src:/app/src'
    environment:
      GRAPHVIS_HOST: 0.0.0.0
    command: nodemon --trace-warnings src/main.js
